proxy:
  flag: true
  addr: 0.0.0.0
services:
  ssh:
    addr: 127.0.0.1:2222
    proxy: :8022
    flag: true
  mysql:
    addr: 127.0.0.1:3366
    proxy: :3306
    flag: true
  redis:
    addr: 127.0.0.1:6380
    proxy: :6379
    flag: true
  web:
    addr: 127.0.0.1:8000
    proxy: :8080
api:
  addr: http://10.10.10.10/
  key: xsec